import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowLeft,ArrowUpRight,Code2,FileCode2,GitBranch,LayoutGrid,LockKeyhole,Plus,RefreshCw,ShieldCheck,Wallet,X} from 'lucide-react';
import {demoJobs,formatGEN,names,nextDemo,short,type Job} from './model';
import {checkPending,connect,discoverWallets,pendingKey,lastTransactionKey,read,send,verifyDeployment,type Deployment,type Pending,type Session,type WalletOption} from './chain';
import {NewCommitment,PatchForm,ReviewForm} from './forms';
import {usePatchTools} from './webmcp';
import {formatError} from './errors';
import {EvidenceVerification} from './EvidenceVerification';

const demoKey='patchbond:walkthrough:v1';
const explorer='https://explorer-studio.genlayer.com';
function loadDemo(){try{const x=JSON.parse(localStorage.getItem(demoKey)||'null');if(Array.isArray(x)&&x.every(j=>j.id&&Array.isArray(j.reviews)&&Array.isArray(j.requirements)))return x as Job[];}catch{/* Start a fresh walkthrough if storage is unavailable. */}return demoJobs();}
function loadPending(){try{return JSON.parse(localStorage.getItem(pendingKey)||'null') as Pending|null;}catch{return null;}}
function loadLastTransaction(){try{const t=JSON.parse(localStorage.getItem(lastTransactionKey)||'null');return /^0x[0-9a-fA-F]{64}$/.test(t?.hash||'')&&['success','error'].includes(t?.outcome)?t as Pending&{outcome:'success'|'error'}:null;}catch{return null;}}
function Modal({title,busy,close,children}:{title:string;busy:boolean;close:()=>void;children:ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
 return <dialog ref={ref} aria-labelledby="modal-title" onCancel={e=>{e.preventDefault();if(!busy)close();}} onClick={e=>{if(e.target===e.currentTarget&&!busy)close();}}><div className="dialog-inner"><header><h2 id="modal-title">{title}</h2><button aria-label="Close dialog" disabled={busy} onClick={close}><X size={22}/></button></header>{children}</div></dialog>;
}

export default function Workspace(){
 const [demo,setDemo]=useState(loadDemo),[liveJobs,setLiveJobs]=useState<Job[]>([]),[liveJob,setLiveJob]=useState<Job|null>(null);
 const [mode,setMode]=useState<'demo'|'live'>(()=>new URLSearchParams(location.search).get('mode')==='demo'?'demo':'live');
 const [selected,setSelected]=useState(()=>new URLSearchParams(location.search).get('job')||''),[filter,setFilter]=useState('All patches'),[search,setSearch]=useState('');
 const [deployment,setDeployment]=useState<Deployment|null>(null),[session,setSession]=useState<Session|null>(null),[wallets,setWallets]=useState<WalletOption[]>([]),[pending,setPending]=useState<Pending|null>(loadPending),[lastTransaction,setLastTransaction]=useState(loadLastTransaction);
 const [modal,setModal]=useState(''),[busy,setBusy]=useState(false),[refreshing,setRefreshing]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[role,setRole]=useState<'client'|'author'>('client'),[credit,setCredit]=useState('0');
 const [tick,setTick]=useState(Date.now()),[offset,setOffset]=useState(0),[claims,setClaims]=useState<string[]>([]);const generation=useRef(0),lock=useRef(false);
 const isDemo=mode==='demo',jobs=isDemo?demo:liveJobs,job=isDemo?demo.find(j=>j.id===selected)||null:liveJob,now=Math.floor(tick/1000)+(isDemo?offset:0);
 const account=isDemo?'0x'+(role==='author'?'2':'1').repeat(40):session?.address||'';
 const enabled=isDemo||!!(deployment?.verified&&session&&!pending),last=job?.reviews.at(-1);
 useEffect(()=>{const timer=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{try{localStorage.setItem(demoKey,JSON.stringify(demo));}catch{setError('Walkthrough storage is unavailable. Changes may not survive a refresh.');}},[demo]);
 useEffect(()=>{fetch('/deployment.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Deployment configuration unavailable.');return r.json();}).then(setDeployment).catch(e=>setError(formatError(e)));return discoverWallets(setWallets);},[]);
 useEffect(()=>{const listener=()=>{setPending(loadPending());setLastTransaction(loadLastTransaction());};window.addEventListener('storage',listener);return()=>window.removeEventListener('storage',listener);},[]);
 useEffect(()=>{if(!session)return;const changed=()=>{setSession(null);setCredit('0');setMessage('Wallet changed. Reconnect to confirm your account and network.');};session.provider.on?.('accountsChanged',changed);session.provider.on?.('chainChanged',changed);return()=>{session.provider.removeListener?.('accountsChanged',changed);session.provider.removeListener?.('chainChanged',changed);};},[session]);
 useEffect(()=>{const back=()=>{const p=new URLSearchParams(location.search);setSelected(p.get('job')||'');setMode(p.get('mode')==='demo'?'demo':'live');};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back);},[]);
 function navigate(id:string,newMode=mode){generation.current++;setLiveJob(null);setSelected(id);setMode(newMode);setError('');const p=new URLSearchParams();p.set('mode',newMode);if(id)p.set('job',id);history.pushState({},'',`?${p}`);window.scrollTo({top:0});}
 usePatchTools(jobs,mode,navigate);
 async function refresh(){if(isDemo||!deployment?.verified)return;const token=++generation.current;setRefreshing(true);try{await verifyDeployment(deployment);const list=await read<Job[]>(deployment,'list_jobs',[0,50]);const detail=selected?await read<Job>(deployment,'get_job',[selected]):null;const ledger=session?await read<{claimable:string}>(deployment,'get_accounting',[session.address]):{claimable:'0'};if(token===generation.current){setLiveJobs(list);setLiveJob(detail);setCredit(ledger.claimable);}}catch(e){if(token===generation.current)setError(`Reading finalized StudioNet state: ${formatError(e)}`);}finally{if(token===generation.current)setRefreshing(false);}}
 useEffect(()=>{void refresh();return()=>{generation.current++;};},[mode,deployment,selected,session]);
 useEffect(()=>{if(!pending||isDemo)return;let cancelled=false;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{if(cancelled)return;if(lock.current){timer=setTimeout(poll,5000);return;}try{const result=await checkPending(pending);if(cancelled)return;if(result!=='pending'){setPending(loadPending());setLastTransaction(loadLastTransaction());if(result==='success')setMessage('Transaction finalized and contract execution succeeded. Refreshing the chain record.');else setError('Transaction did not complete successfully. No success was recorded. Refresh the record before retrying.');await refresh();return;}}catch{/* A network interruption does not mean transaction failure. Keep its hash and retry. */}if(!cancelled)timer=setTimeout(poll,5000);};timer=setTimeout(poll,5000);return()=>{cancelled=true;clearTimeout(timer);};},[pending,mode,deployment,selected,session]);
 async function run(task:()=>Promise<void>){if(lock.current)throw Error('An action is already in progress.');lock.current=true;setBusy(true);setError('');try{await task();}catch(e){setError(formatError(e));throw e;}finally{lock.current=false;setBusy(false);}}
 function clickTask(task:()=>Promise<void>){void run(task).catch(()=>{});}
 async function transact(method:string,args:unknown[],value='0'){if(!deployment||!session)throw Error('Connect your wallet after a verified deployment is configured.');await send(deployment,session,method,args,value,setPending);setMessage('Transaction submitted. Check its execution result before taking another action.');}
 async function action(method:string,params:Record<string,string>={}){await run(async()=>{if(!job)throw Error('Open a commitment first.');if(isDemo){const updated=nextDemo(job,method,params,role,now);setDemo(all=>all.map(j=>j.id===updated.id?updated:j));setMessage('Walkthrough updated. No transaction or validator call was made.');}else{let args:unknown[]=[job.id];if(method==='submit_patch')args=[job.id,params.head,Number(params.run),Number(params.attempt)];if(method==='review_patch')args=[job.id,job.revision];if(method==='challenge_review')args=[job.id,job.revision,params.statement];await transact(method,args);}setModal('');});}
 async function create(terms:Record<string,unknown>,reward:string){await run(async()=>{if(isDemo){if(demo.some(j=>j.id===terms.id))throw Error('That commitment ID is already in use.');const created={...terms,client:'0x'+'1'.repeat(40),reward,created_at:now,accepted_at:0,revision_due:Number(terms.submit_by)+offset,accept_by:Number(terms.accept_by)+offset,submit_by:Number(terms.submit_by)+offset,expires_at:Number(terms.submit_by)+86400+offset,status:'OPEN',revision:0,challenge_until:0,reviews:[]} as unknown as Job;setDemo(all=>[created,...all]);navigate(created.id);setMessage('Simulated commitment created. No reward was funded.');}else await transact('create_job',[JSON.stringify(terms)],reward);setModal('');});}
 async function check(){await run(async()=>{if(!pending)return;const result=await checkPending(pending);if(result==='pending')setMessage('The transaction is not yet finalized with a confirmed execution result.');else{setPending(loadPending());setLastTransaction(loadLastTransaction());setMessage(result==='success'?'Transaction finalized and contract execution succeeded.':'Transaction failed or was cancelled. No success is recorded.');await refresh();}});}
 function exportRecord(){if(!job)return;const blob=new Blob([JSON.stringify({mode:isDemo?'SIMULATED — NOT CHAIN EVIDENCE':'live',deployment:isDemo?null:deployment,job},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=job.id+(isDemo?'-SIMULATED':'')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const filtered=jobs.filter(j=>(filter==='All patches'||(filter==='Accepted'?j.status==='ACCEPTED':!['ACCEPTED','REFUNDED'].includes(j.status)))&&`${j.id} ${j.title} ${j.repo}`.toLowerCase().includes(search.toLowerCase()));
 const deadline=job?(job.status==='OPEN'?job.accept_by:['IN_PROGRESS','CHANGES_REQUESTED'].includes(job.status)?job.revision_due:job.expires_at):0;
 const remaining=Math.max(0,(job?.challenge_until||0)-now),canRecover=job&&!['REVIEW_PENDING','ACCEPTED','REFUNDED'].includes(job.status)&&now>=deadline;

 return <div className="app"><aside className="sidebar"><button className="brand" onClick={()=>navigate('')} aria-label="PatchBond home"><span className="brand-icon"><Code2 size={25}/></span>PatchBond<span className="version">/ 01</span></button><div className="workspace"><span className="workspace-icon">PB</span><div>Builder workspace<small>GenLayer native</small></div></div><span className="nav-label">WORKSPACE</span><button className="nav-item active" onClick={()=>navigate('')} aria-label="Patch board"><LayoutGrid size={18}/>Patch board<small>{jobs.length}</small></button><button className="nav-item" onClick={()=>setModal('setup')} aria-label="Deployment and policy"><ShieldCheck size={18}/>Deployment & policy</button><div className="sidebar-note"><ShieldCheck size={23}/><strong>Code changes.<br/>Accountability stays.</strong><p>Requirements, evidence and verdicts in one traceable record.</p></div><div className="sidebar-bottom"><span className="avatar">PB</span><div>Your workspace<small>{isDemo?'Local walkthrough':'StudioNet sandbox'}</small></div><LockKeyhole size={15}/></div></aside>
 <main><header className="topbar"><div><button onClick={()=>navigate('')}>Workspace</button><span>/</span><strong>{selected||'Patch board'}</strong></div><div className="top-actions"><div className="mode-switch"><button className={isDemo?'chosen':''} onClick={()=>navigate('','demo')}>Walkthrough</button><button className={!isDemo?'chosen':''} onClick={()=>navigate('','live')}>Live StudioNet</button></div>{!isDemo&&<button className="secondary" onClick={()=>setModal('wallet')}><Wallet size={16}/>{session?short(session.address):'Connect wallet'}</button>}</div></header>
 <div className="content"><div className="notice"><span><strong>{isDemo?'Walkthrough · simulated.':deployment?.verified?'StudioNet · simulated GEN.':'Live deployment not configured.'}</strong> {isDemo?'Examples are stored in this browser. No validators run and no funds move.':'No real-value funds. Live actions require a matching, verified contract.'}</span><button onClick={()=>setModal('setup')}>View policy <ArrowUpRight size={14}/></button></div>
 {error&&<div className="feedback error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}{message&&<div className="feedback" role="status">{message}<button aria-label="Dismiss update" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 {!isDemo&&lastTransaction&&(!selected||lastTransaction.jobId===selected)&&<div className={'feedback'+(lastTransaction.outcome==='error'?' error':'')}><span>Last confirmed StudioNet result: {lastTransaction.outcome==='success'?'execution succeeded':'failed or cancelled'} · {lastTransaction.method} · {lastTransaction.jobId} · <a href={`${explorer}/transactions/${lastTransaction.hash}`} target="_blank" rel="noreferrer">View transaction ↗</a></span></div>}
 {!isDemo&&pending&&<div className="pending"><div><strong>Transaction awaiting verification</strong><p>{pending.method} · {pending.jobId} · <a href={`${explorer}/transactions/${pending.hash}`} target="_blank" rel="noreferrer">{short(pending.hash)} ↗</a></p></div><button className="secondary" disabled={busy} onClick={()=>void check().catch(()=>{})}><RefreshCw size={15}/>Check transaction</button></div>}
 {!selected?<><div className="page-heading"><div><span className="eyebrow">ACCOUNTABLE CODE REPAIR</span><h1>Patch board<span className="title-dot">.</span></h1><p>One bug. A bounded patch. An independently reviewed result.</p></div><button className="primary" disabled={busy||(!isDemo&&!deployment?.verified)} onClick={()=>setModal(!isDemo&&!session?'wallet':'new')}><Plus size={17}/>New commitment</button></div>
 <div className="metrics"><div><span>Patch commitments</span><strong>{String(jobs.length).padStart(2,'0')}<Code2 size={21}/></strong><small>{isDemo?'Simulated examples':'First 50 finalized records'}</small></div><div><span>Awaiting a verdict</span><strong>{String(jobs.filter(j=>['REVIEW_READY','REVIEW_PENDING'].includes(j.status)).length).padStart(2,'0')}<GitBranch size={21}/></strong><small>Evidence ready or under review</small></div><div><span>Challenge window</span><strong>10<span className="unit">min</span><ShieldCheck size={21}/></strong><small>Before a decision can finalize</small></div></div>
 <div className="list-heading"><div className="filter-tabs">{['All patches','Active','Accepted'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><input className="search" aria-label="Search commitments" placeholder="Search commitments…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="job-list"><div className="list-labels"><span>COMMITMENT / REPOSITORY</span><span>STATUS</span><span>REWARD</span><span/></div>{filtered.map(j=><button className="job-row" key={j.id} onClick={()=>navigate(j.id)}><span className="job-main"><span className="file-icon"><FileCode2 size={23}/></span><span><small>{j.id}</small><strong>{j.title}</strong><span className="repo"><GitBranch size={13}/>{j.repo}</span></span></span><span className={'status '+j.status.toLowerCase()}>{names[j.status]}</span><span className="reward">{formatGEN(j.reward)}<small>test GEN{isDemo?' · simulated':''}</small></span><ArrowUpRight size={20}/></button>)}{!filtered.length&&<div className="empty"><FileCode2 size={30}/><h2>{!isDemo&&!deployment?.verified?'Your live workspace is not activated':'No matching commitments'}</h2><p>{!isDemo&&!deployment?.verified?'Explore the walkthrough while contract deployment and live verification are pending.':'Try another search or create a commitment.'}</p><button className="secondary" onClick={()=>isDemo?setSearch(''):setModal('setup')}>{isDemo?'Clear search':'Deployment checklist'}</button></div>}</div>
 <div className="board-footer"><ShieldCheck size={17}/><span>The model evaluates the patch. The contract determines the amount.</span><span>NO ADMIN VERDICT OVERRIDE</span></div><section className="principles"><div><span>01</span><h3>Freeze the scope</h3><p>Pin the base commit, requirements and trusted CI workflow.</p></div><div><span>02</span><h3>Inspect the evidence</h3><p>Retain before-and-after code, provenance and every revision.</p></div><div><span>03</span><h3>Finalize by the rules</h3><p>Fixed reward on acceptance. A bounded correction and expiry recovery.</p></div></section>{isDemo&&<button className="text-button" onClick={()=>setModal('reset')}>Reset simulated workspace</button>}</>:<>
 <button className="back" onClick={()=>navigate('')}><ArrowLeft size={16}/>All patches</button>{!job?<section className="empty"><h2>{refreshing?'Loading finalized chain state…':'Commitment unavailable in this mode'}</h2><p>Choose a record from the patch board. Simulated and live records never share state.</p></section>:<><div className="page-heading"><div><span className="eyebrow">{job.id} · REVISION {job.revision}</span><h1 className="detail-title">{job.title}</h1><p><GitBranch size={15}/>{job.repo}</p></div><span className={'status '+job.status.toLowerCase()}>{names[job.status]}</span></div>
 <div className="detail-toolbar">{isDemo?<label>Act as<select aria-label="Walkthrough role" value={role} onChange={e=>setRole(e.target.value as 'client'|'author')}><option value="client">Demo client</option><option value="author">Demo patch author</option></select></label>:<button className="secondary" disabled={refreshing||busy} onClick={()=>void refresh()}><RefreshCw size={15}/>Refresh chain state</button>}<button className="secondary" onClick={exportRecord}>Export {isDemo?'simulated ':''}record</button></div>
 {!isDemo&&<EvidenceVerification key={job.id} jobId={job.id} deployment={deployment}/>}
 <div className="detail-grid"><div><section className="panel"><div className="panel-title"><FileCode2 size={19}/><h2>The frozen brief</h2><span><LockKeyhole size={13}/>Immutable</span></div>{job.bug&&<p className="bug">{job.bug}</p>}{job.requirements.map((r,i)=><div className="requirement" key={i}><span>R{i+1}</span><p>{r}</p></div>)}<div className="meta-row"><span>Base commit</span><code title={job.base_sha}>{short(job.base_sha)}</code></div><div className="meta-row"><span>Allowed files</span><code>{job.allowed_paths.join(', ')}</code></div><details><summary>Source & CI provenance policy</summary><dl><dt>Workflow</dt><dd>{job.workflow_path}</dd><dt>SHA-256</dt><dd><code>{job.workflow_sha256}</code></dd><dt>Exact bytes / workflow ID</dt><dd>{job.workflow_bytes} / {job.workflow_id}</dd><dt>Required job</dt><dd>{job.required_job}</dd></dl><p>GitHub is the registered evidence authority. A passing job does not by itself prove the fix is correct.</p></details></section>
 <section className="panel action-panel"><span className="eyebrow">NEXT ACTION</span><h2>{names[job.status]}</h2>
 {job.status==='OPEN'&&<><p>The assigned author must accept before {new Date(job.accept_by*1000).toLocaleString()}.</p><button className="primary" disabled={!enabled||busy||account!==job.author||now>=job.accept_by} onClick={()=>void action('accept_job').catch(()=>{})}>Accept assignment</button>{account!==job.author&&<p className="hint">{isDemo?'Switch to Demo patch author above.':'Connect the assigned author wallet.'}</p>}</>}
 {['IN_PROGRESS','CHANGES_REQUESTED'].includes(job.status)&&<><p>{job.revision?'One correction remains. Submit a new commit; the original evidence is retained.':'Attach the exact patch commit and its completed CI attempt.'}</p><button className="primary" disabled={!enabled||busy||account!==job.author||now>=job.revision_due} onClick={()=>setModal('patch')}>Submit {job.revision?'corrected patch':'patch evidence'}</button><p className="hint">{account!==job.author?(isDemo?'Switch to Demo patch author above.':'Only the assigned author may submit.'):`Due ${new Date(job.revision_due*1000).toLocaleString()}`}</p></>}
 {job.status==='REVIEW_READY'&&<><p>Review checks every mandatory requirement and the allowed scope against the captured evidence.</p><button className="primary" disabled={!enabled||busy||now+600>=job.expires_at} onClick={()=>setModal('review')}>{isDemo?'Simulate GenLayer review':'Request GenLayer review'}</button></>}
 {job.status==='REVIEW_PENDING'&&<><p>Proposed outcome: <strong>{last?.outcome?.replaceAll('_',' ').toLowerCase()}</strong></p><div className="countdown">{remaining?`${Math.floor(remaining/60)}m ${remaining%60}s remaining`:'Ready to finalize'}<small>{isDemo?'Walkthrough clock only.':'The contract enforces this deadline.'}</small></div><div className="button-row"><button className="primary" disabled={!enabled||busy||remaining>0} onClick={()=>void action('finalize').catch(()=>{})}>Finalize decision</button>{!last?.challenge_used&&remaining>0&&<button className="secondary" disabled={!enabled||busy||![job.client,job.author].includes(account)} onClick={()=>setModal('challenge')}>Challenge review</button>}</div>{isDemo&&remaining>0&&<button className="text-button" onClick={()=>setOffset(x=>x+remaining+1)}>Skip wait in walkthrough</button>}{last?.challenge_used&&<p>One challenge has been used for this revision.</p>}</>}
 {['ACCEPTED','REFUNDED'].includes(job.status)&&<><p>{job.status==='ACCEPTED'?'The fixed reward is credited to the author.':'The fixed reward is credited back to the client.'} Withdrawal is a separate action.</p><button className="primary" disabled={!enabled||busy||(isDemo?(claims.includes(job.id)||account!==(job.recipient||(job.status==='ACCEPTED'?job.author:job.client))):BigInt(credit)<=0n)} onClick={()=>clickTask(async()=>{if(isDemo){setClaims(x=>[...x,job.id]);setMessage('Simulated withdrawal completed. No funds moved.');}else await transact('withdraw',[]);})}>{isDemo?(claims.includes(job.id)?'Simulated reward claimed':'Simulate withdrawal'):`Withdraw ${formatGEN(credit)} test GEN`}</button>{isDemo&&<p className="hint">Act as the {job.status==='ACCEPTED'?'author':'client'} to simulate this withdrawal. Demo claims reset on page reload.</p>}</>}
 {canRecover&&<button className="secondary" disabled={!enabled||busy} onClick={()=>void action('recover_expired').catch(()=>{})}>Recover expired reward to client</button>}
 </section>
 <section className="panel"><div className="panel-title"><GitBranch size={19}/><h2>Evidence & review history</h2><span>{job.reviews.length} revisions</span></div>{!job.reviews.length?<p className="hint">No patch evidence recorded yet.</p>:job.reviews.map(r=><details className="revision" key={r.revision} open={r.revision===job.revision}><summary>Revision {r.revision} · {r.outcome?.replaceAll('_',' ')||'Evidence captured'}</summary><div className="meta-row"><span>Patch commit</span><code>{short(r.head_sha)}</code></div><div className="meta-row"><span>CI run / attempt</span><code>{r.run_id} / {r.attempt}</code></div><p className="digest">{isDemo?'SIMULATED — not live evidence':`Evidence SHA-256: ${r.evidence_hash}`}</p>{r.checks?.map(c=><div className="check" key={c.id}><strong>{c.id} · {c.status}</strong><p>{c.reason}</p>{c.quote&&<pre>{c.quote}</pre>}</div>)}{r.challenge&&<blockquote>{r.challenge}</blockquote>}{r.assessments?.map((a,i)=><p className="hint" key={i}>{a.kind} · {new Date(a.at*1000).toLocaleString()} · {a.result.outcome.replaceAll('_',' ')}</p>)}{r.evidence&&<details><summary>Captured evidence JSON</summary><pre>{JSON.stringify(r.evidence,null,2)}</pre></details>}</details>)}</section></div>
 <aside className="panel settlement"><Wallet size={23}/><span className="eyebrow">FIXED REWARD{isDemo?' · SIMULATED':''}</span><h2>{formatGEN(job.reward)} <small>test GEN</small></h2><p>Only the precommitted amount can be credited. The model cannot choose a payout or an address.</p><div className="meta-row"><span>Client</span><strong>{isDemo?'Demo client':short(job.client)}</strong></div><div className="meta-row"><span>Patch author</span><strong>{isDemo?'Demo patch author':short(job.author)}</strong></div><div className="meta-row"><span>Challenge window</span><strong>10 minutes</strong></div><div className="meta-row"><span>Correction attempts</span><strong>1</strong></div><div className="meta-row"><span>Protocol fee</span><strong>0%</strong></div><div className="safe-note"><LockKeyhole size={15}/>{isDemo?'No real funds or validator results.':'StudioNet only · no real-value funds.'}</div></aside></div></>}</>}
 </div></main>
 {modal&&<Modal busy={busy} title={({new:'Create a patch commitment',patch:`Record patch · revision ${(job?.revision||0)+1}`,review:'Review the patch',challenge:'Challenge this review',wallet:'Connect your wallet',setup:'Deployment & evidence policy',reset:'Reset the walkthrough'})[modal]||''} close={()=>setModal('')}>
 {modal==='new'&&<NewCommitment demo={isDemo} client={account} busy={busy} onSubmit={create}/>}{modal==='patch'&&job&&<PatchForm job={job} demo={isDemo} busy={busy} onSubmit={p=>action('submit_patch',p)}/>}{['review','challenge'].includes(modal)&&<ReviewForm demo={isDemo} challenge={modal==='challenge'} busy={busy} onSubmit={p=>action(modal==='challenge'?'challenge_review':'review_patch',p)}/>}
 {modal==='wallet'&&<div className="form-stack"><p>Use a test-only account. Connecting requests account access and may ask to switch to StudioNet. It does not transfer funds.</p>{session&&<p>Connected: <code>{session.address}</code></p>}{wallets.map(w=><button className="secondary" key={w.info.uuid} disabled={busy} onClick={()=>clickTask(async()=>{const s=await connect(w);setSession(s);setModal('');setMessage('Wallet connected to StudioNet. Use only simulated GEN.');})}>{w.info.name}</button>)}{!wallets.length&&<p>No wallet provider was detected. Open this app in a browser with your wallet extension installed.</p>}{error&&<div role="alert" className="feedback error">{error}</div>}</div>}
 {modal==='setup'&&<div className="form-stack"><div className="feedback">{deployment?.verified?'StudioNet deployment configured. Source and policy are checked before signing.':'Deployment identity has not been verified. Live signing is blocked.'}</div><p>PatchBond is a GenLayer StudioNet project. Native GEN balances here are simulated; there is no production or real-money settlement.</p>{deployment?.address&&<p><a href={`${explorer}/address/${deployment.address}`} target="_blank" rel="noreferrer">View Intelligent Contract ↗</a></p>}<h3>Bounded first release</h3><ul><li>Public GitHub repository; one assigned author; one direct-child commit of the base.</li><li>Up to four modified files and 24 KB of combined source and workflow evidence. No added, deleted or renamed files.</li><li>Immutable workflow hash and exact required job. Every required-job step must complete successfully.</li><li>Validators independently compare all requirement statuses, scope and the derived outcome.</li><li>One correction, one challenge per revision, and a 10-minute challenge window.</li><li>Fixed simulated GEN reward, separate withdrawal, no admin verdict override.</li></ul><h3>Trust boundary</h3><p>GitHub authenticates repository and CI metadata. The client must audit the pinned workflow and its dependencies. A green check is not proof of correctness; validators do not execute submitted code. Ambiguity cannot produce acceptance. Hosted StudioNet is a sandbox and its data may be reset.</p><h3>Start a StudioNet commitment</h3><ol><li>Connect a dedicated test wallet on StudioNet (chain 61999).</li><li>Use the <a href="https://studio.genlayer.com" target="_blank" rel="noreferrer">Studio account faucet</a> for simulated GEN. Never send real-value funds.</li><li>Register a real public repository and an audited, commit-pinned workflow. The assigned author needs GitHub push access separately.</li></ol><p>Use test-only externally owned wallets for withdrawals. Smart-contract recipients and production networks are outside this release.</p><p><a href="https://github.com/Demigodd00/patchbond" target="_blank" rel="noreferrer">App &amp; contract source ↗</a> · <a href="/verification.json" target="_blank" rel="noreferrer">Recorded verification results ↗</a> · <a href="https://github.com/Demigodd00/patchbond-studionet-fixtures" target="_blank" rel="noreferrer">Public CI fixtures ↗</a></p></div>}
 {modal==='reset'&&<div className="form-stack"><p>This replaces only the simulated records in this browser. Live records and pending transactions are not changed.</p><button className="primary" onClick={()=>{setDemo(demoJobs());setOffset(0);setClaims([]);navigate('','demo');setModal('');setMessage('The simulated workspace has been reset.');}}>Reset simulated records</button></div>}
 </Modal>}
 </div>;
}
